# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: |
        cd my-app
        mvn package
        java -cp target/my-app-1.0-SNAPSHOT.jar com.mycompany.app.App
    
  #  - name: Check Files
 #   run: |
 #       cd my-app
  #      ls -a
   #     cd target 
    #    ls -a
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: github-actions-artifacts
        path: my-app/target/my-app-1.0-SNAPSHOT.jar
   
    - name: Build And Push To DockerHub
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: edadon/dockerstore
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Docker Pull
      run: docker pull edadon/dockerstore:master-6efb035
    - name: Check Files
      run: |
        cd my-app
        ls -a
        cd target 
        ls -a
